version: '3.7'
services:
  smarthome:
    image: mikmuellerdev/smarthome:latest
    container_name: smarthome
    depends_on:
      - "smarthome-mariadb"
    hostname: smarthome
    environment:
      - SMARTHOME_ADMIN_PASSWORD=password
      - SMARTHOME_DB_HOSTNAME=smarthome-mariadb
      - SMARTHOME_DB_PASSWORD=password
      - SMARTHOME_DB_USER=smarthome
      - SMARTHOME_DB_DATABASE=smarthome
      - SMARTHOME_DB_PORT=3306
      - SMARTHOME_PORT=80 #Override the port on which smarthome runs on internally
    ports:
    - 8123:80 #should be the same as SMARTHOME_PORT
    restart: unless-stopped
    volumes:
      - smarthome_data:/app/data/

  smarthome-mariadb:
    image: mariadb
    container_name: smarthome-mariadb
    hostname: smarthome-db
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - TZ=Europe/Berlin
      - MARIADDB_DATABASE=smarthome
      - MARIADDB_USER=smarthome
      - MARIADDB_PASSWORD=password
    restart: unless-stopped